{
  "apiUrlRoot": "https://${orch_hostname}",
  "leonardoUrlRoot": "https://${leonardo_hostname}",
  "samUrlRoot": "https://${sam_hostname}",
  "googleClientId": "${refresh_token_client_id}",
  "isDebug": true,
  "shibbolethUrlRoot": "http://mock-nih.dev.test.firecloud.org",
  "tcgaNamespace": "broad-firecloud-tcga-${google_project}",
  "workflowCountWarningThreshold": 100,
  "submissionStatusRefresh": 60000,
  "userGuideUrl": "https://software.broadinstitute.org/firecloud/documentation/",
  "userNotebooksGuideUrl": "https://software.broadinstitute.org/firecloud/documentation/quickstart?page=notebooks",
  "forumUrl": "http://gatkforums.broadinstitute.org/firecloud",
  "billingAccountGuideUrl": "http://gatkforums.broadinstitute.org/firecloud/discussion/9762/howto-set-up-a-google-billing-account-non-broad-users",
  "billingProjectGuideUrl": "https://gatkforums.broadinstitute.org/firecloud/discussion/9763/howto-create-a-new-firecloud-billing-project",
  "callCachingGuideUrl": "http://gatkforums.broadinstitute.org/firecloud/discussion/9313/call-caching",
  "googleBucketUrl": "${alerts_bucket_url}/",
  "dockstoreApiUrl": "https://staging.dockstore.org/api",
  "dockstoreWebUrl": "https://staging.dockstore.org",
  "bondUrl": "${bond_url}",
  "marthaFileSummaryUrl": "${file_summary_url}",
  "marthaUrl": "${martha_url}",
  "tosUrl": "${tos_url}",
  "tosApplicationName": "FireCloud",
  "tosVersion": 20180629.1,
  "terraBaseUrl": "${terra_url}",
  "terraRedirectsEnabled": true
}